{
 "title": "DHT22",
 "description": "Monitoramento de Temperatura do sensor DHT22",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperatura atual",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT tempc FROM temperatura " }
   ]
  },
  {
   "title": "Gráfico da Temperatura (°C) ao longo do tempo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT tempc, hora FROM temperatura"
    }
   ]
  },
  {
   "title": "Alarme de Temperatura Alta",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT alta, hora FROM temperatura"
    }
   ]
  },
  {
   "title": "Alarme de Temperatura Baixa",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT baixa, hora FROM temperatura"
    }
   ]
  },
  {
   "title": "Tabela Temperatura ao longo do tempo",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT tempc, hora FROM temperatura ORDER BY hora DESC LIMIT 50 "
    }
   ]
  }
 ]
}